### PR TITLE
add support for Neubrex das format

### PR DESCRIPTION
**Pull request by d-chambers**
## Description

This PR adds support for a Neubrex DAS file which was shared from a student at CSM. Unfortunately, it is entirely different from the Neubrex DTS/DSS support we implemented in #411, but simple enough to support.

## Checklist

I have (if applicable):

- [ ] referenced the GitHub issue this PR closes.
- [x] documented the new feature with docstrings or appropriate doc page.
- [x] included a test. See [testing guidelines](https://dascore.org/contributing/testing.html).
- [ ] your name has been added to the contributors page (docs/contributors.md).
- [x] added the "ready_for_review" tag once the PR is ready to be reviewed.

### CODE REVIEW

**Review by ahmadtourei — APPROVED** [review]
Looks great! One general suggestion: it would be beneficial to enhance the class naming conventions in the [IO module](https://dascore.org/api/dascore/io.html) down the road as we're expanding IO capabilities to DSS and DTS formats. This would be particularly useful in the homepage documentation helping users quickly know if their data type/format of interest is implemented.

**Comment by d-chambers** [comment]
> Looks great! One general suggestion: it would be beneficial to enhance the class naming conventions in the [IO module](https://dascore.org/api/dascore/io.html) down the road as we're expanding IO capabilities to DSS and DTS formats. This would be particularly useful in the homepage documentation helping users quickly know if their data type/format of interest is implemented.

Yes, this is probably a good idea. However, from what I can tell, the other Neubrex file format (currently used for DSS and DTS at forge) would have worked just fine for DAS data as well. I am not 100% sure if they have different formats for DAS and DTS or maybe they just have different formats that are sometimes used for either, or maybe they are just different versions of the same format? 

I really wish everyone would include a name of the file format and a version code in the headers so we don't have to guess at these things. 

I am dragging my feet a bit on merging this until I have some more time to think about it. If anyone knows someone at Neubrex that would be willing to help us figure out the best approach here that would be useful.

**Comment by arturguzik** [comment]
Derrick, I'm about to respond to you over mail, with comments on our (Neubrex) format. Both RFS and DAS.

**Comment by d-chambers** [comment]
Hi @arturguzik, I got your email. I will take a closer look in the next few days and get back to you if I have any questions. Thanks in advance for the help.

**Pull request merged**
