### PR TITLE
read pubdas TDMS

### PR DESCRIPTION
**Pull request by d-chambers**
## Description
 So it appears the TDMS version, or at least the attributes, are different from our TDMS test file and the ones in pubdas. This PR fixes the issue by changing how distances are determined.

@aissah, do you mind reviewing this? 

## Checklist

I have (if applicable):

- [ ] referenced the GitHub issue this PR closes.
- [ ] documented the new feature with docstrings or appropriate doc page.
- [ ] included a test. See [testing guidelines](https://dascore.org/contributing/testing.html).
- [ ] your name has been added to the contributors page (docs/contributors.md).
- [ ] added the "ready_for_review" tag once the PR is ready to be reviewed.

### CODE REVIEW

**Comment by aissah** [comment]
I am a bit confused about what the issue is. We had one test file that you got from Silixa, I think and another that I made from the FORESEE dataset. Which of them is mismatched with that on PUBDAS?
Also, the FORESEE dataset was reformatted and uploaded as hdf5. Which other dataset on PUBDAS uses TDMS, maybe Silixa somehow allows customization of attributes for different datasets?
Lastly, is it that some of the attributes are missing or they are saved under different "keys"?

**Comment by d-chambers** [comment]
> Which of them is mismatched with that on PUBDAS?

Maybe both? The problem is that the Fossa TDMS files don't have "Start Distance (m)" and "Stop Distance (m)" in their attrs and I didn't see anything similar. But all the TDMS files I have seen so far do have "StartPosition[m]" and "n_channels" which prompted the change [here](https://github.com/DASDAE/dascore/pull/231/files#).

I am not sure if you can add custom attrs to the TDMS file or if we are just seeing a slightly different version of TDMS data.

 I just wanted your feedback to see if you know of any issues that might crop up by doing it this way.

**Comment by aissah** [comment]
That seems like a reasonable fix to me. We'll just have to wait and see 😅.

**Comment by d-chambers** [comment]
> We'll just have to wait and see 

Ya, or actually read the TDMS spec 😝. Will merge for now since the change still allows us to read our test files **and** the TDMS files in original PubDAS datasets.

**Pull request merged**
