### PR TITLE
refactor wiggle plot

### PR DESCRIPTION
**Pull request by d-chambers**
## Description

This PR fixes issue #114 and simplifies the wiggle plot code. They look slightly different now, but the docs correctly display the images and the plotting is much more efficient.

image

@aissah, could you please take a look at this sometime in the next week or so and let me know what you think? 

## Checklist

I have (if applicable):

- [x] referenced the GitHub issue this PR closes.
- [x] documented the new feature with docstrings or appropriate doc page.
- [x] included a test. See [testing guidelines](https://dascore.org/contributing/testing.html).
- [x] your name has been added to the contributors page (docs/contributors.md).
- [x] added the "ready_for_review" tag once the PR is ready to be reviewed.

### CODE REVIEW

**Comment by d-chambers** [comment]
Todo: 

- [ ] Add alpha parameter, default 0.2 (ish)
- [ ] shade parameter
- [ ] fix y axis label density

**Comment by aissah** [comment]
I fixed the density of the labels on the y-axis and made it a maximum of 30. I added the option for shading the peaks and set the alpha for that to 0.6 because it seemed the most visually appealing to me, maybe you can take a look at that. @d-chambers

**Comment by d-chambers** [comment]
Hmmm, still doesn't look quite right for a small number of traces:

image

In this case I would expect the distance labels to line up with the center of the traces. I think I have an idea how to fix it though, I will give it a go.

**Comment by aissah** [comment]
Did the last commit fix it?

**Comment by d-chambers** [comment]
> Did the last commit fix it?

No, I just added a test to make sure the shading part of the code gets run. I am still working on it.

**Comment by d-chambers** [comment]
Ok, I played around with plotting several kinds of patches and made two small adjustments:

1. I added alpha as a parameter to `wiggle`. I hate to add more parameters but I found this was one I needed to adjust depending on the number of channels, how much they were touching, etc.
2. I changed the max number of y axis labels from 30 to 10, which seemed more reasonable for some smaller sized plots, but the larger ones still looked fine. These can also be manipulated manually with the returned axis. 

I couldn't quite get the plot above to look good because the date axis formatting is different from a non-date axis. It is probably an edge case that doesn't merit a lot of time though.

Overall, I think there are still some improvements we can make in the future but to me it looks good for now.

**Comment by d-chambers** [comment]
I am going to merge this for now, we can make any changes in a future PR.

**Pull request merged**
