### PR TITLE
Map plot

### PR DESCRIPTION
**Pull request by aissah**
## Description

I added "plot_map", a visualization function that plots the layout of a cable colored by a particular parameter. 

## Checklist

I have (if applicable):

- [ ] referenced the GitHub issue this PR closes.
- [x] documented the new feature with docstrings or appropriate doc page.
- [x] included a test. See [testing guidelines](https://dascore.org/contributing/testing.html).
- [x] your name has been added to the contributors page (docs/contributors.md).
- [ ] added the "ready_for_review" tag once the PR is ready to be reviewed.

### CODE REVIEW

**Comment by d-chambers** [comment]
Nice work @aissah, it looks very configurable. Do you mind posting an example of the output here so we can see what it looks like?

**Comment by d-chambers** [comment]
Looks great!

**Comment by d-chambers** [comment]
Except, why is latitude in ft and longitude in m?

**Comment by ahmadtourei** [comment]
A quick suggestion: since we don't use `plot` in viz's modules (wiggle, waterfall, and spectrogram), I suggest using something like `map_fiber` instead to make it consistent.

**Comment by aissah** [comment]
> Except, why is latitude in ft and longitude in m?

This was an arbitrary choice 😅 illustrating that they can have some units. Would you recommend I change it?

> A quick suggestion: since we don't use `plot` in viz's modules (wiggle, waterfall, and spectrogram), I suggest using something like `map_fiber` instead to make it consistent. What do you think?

I think this is a good idea. What do you think @d-chambers ?

**Comment by d-chambers** [comment]
> I think this is a good idea. What do you think @d-chambers 

Ya, that sounds like a better name to me!

**Comment by d-chambers** [comment]
> This was an arbitrary choice 😅 illustrating that they can have some units. Would you recommend I change it?

Nope, that's perfect. I just wanted to make sure it will use the correct units when we do an actual plot.

**Comment by aissah** [comment]
> > I think this is a good idea. What do you think @d-chambers
> 
> Ya, that sounds like a better name to me!

Done! I think we might be ready to merge after the checks

**Review by d-chambers — APPROVED** [review]

**Pull request merged**
