### PR TITLE
Raise spool.viz

### PR DESCRIPTION
**Pull request by ahmadtourei**
## Description

This PR implements a detailed `AttributeError` when `Spool.viz` is used, directing users to use `Patch.viz` instead for data visualization.

## Checklist

I have (if applicable):

- [ ] referenced the GitHub issue this PR closes.
- [ ] documented the new feature with docstrings or appropriate doc page.
- [ ] included a test. See [testing guidelines](https://dascore.org/contributing/testing.html).
- [ ] your name has been added to the contributors page (docs/contributors.md).
- [ ] added the "ready_for_review" tag once the PR is ready to be reviewed.

### CODE REVIEW

**Comment by d-chambers** [comment]
Thanks for opening a new PR @ahmadtourei.

Ok, so I didn't understand why raising a custom  `AttributeError` when a `spool.viz` is accessed is not sufficient here? 

eg

```python 
@property
def viz(self):
    raise AttributeError("spool has no viz namespace, perhaps you meant Patch.viz?")
```

Maybe you are envisioning adding spool visualization methods? In that case we might need to support the `spool.viz` namespace and just raise when `.waterfall` is accessed to address the mistake in the dascore diagram?

**Comment by ahmadtourei** [comment]
> Thanks for opening a new PR @ahmadtourei.
> 
> Ok, so I didn't understand why raising a custom `AttributeError` when a `spool.viz` is accessed is not sufficient here?
> 
> eg
> 
> ```python
> @property
> def viz(self):
>     raise AttributeError("spool has no viz namespace, perhaps you meant Patch.viz?")
> ```
> 
> Maybe you are envisioning adding spool visualization methods? In that case we might need to support the `spool.viz` namespace and just raise when `.waterfall` is accessed to address the mistake in the dascore diagram?

Agreed. The problem was the test I implemented. Please have a look at the new test and let me know if it looks good.

**Review by d-chambers — APPROVED** [review]
Looks good. 

If we want to make spool viz method later we can always modify this.

**Comment by d-chambers** [comment]
The test failures are a problem with the macos scipy build and nothing related to your changes. I will try to take a look tomorrow

**Comment by ahmadtourei** [comment]
> The test failures are a problem with the macos scipy build and nothing related to your changes. I will try to take a look tomorrow

Thanks for the discussion on debugging test failures today! All tests pass.

**Pull request merged**
